"""Initial schema

Revision ID: b953b1744e60
Revises: 
Create Date: 2025-11-03 18:12:23.308637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = 'b953b1744e60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_texts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('document_texts', 'full_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Complete extracted text content from the document',
               existing_nullable=False)
    op.alter_column('document_texts', 'text_length',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Character count of extracted text',
               existing_nullable=False)
    op.alter_column('document_texts', 'extraction_method',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Method used for extraction: docling (native), docling_ocr (OCR applied), or fallback',
               existing_nullable=False)
    op.alter_column('document_texts', 'extraction_engine',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Specific engine used: easyocr, tesseract, rapidocr, or native text extraction',
               existing_nullable=True)
    op.alter_column('document_texts', 'extraction_quality',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Confidence score 0.0-1.0 indicating extraction quality',
               existing_nullable=True)
    op.alter_column('document_texts', 'pages_with_ocr',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='Count of pages that required OCR processing',
               existing_nullable=True)
    op.drop_index('idx_document_texts_document_id', table_name='document_texts')
    op.drop_index('idx_document_texts_extracted_at', table_name='document_texts')
    op.drop_index('idx_document_texts_extraction_method', table_name='document_texts')
    op.drop_index('idx_document_texts_extraction_quality', table_name='document_texts', postgresql_where='(extraction_quality IS NOT NULL)')
    op.drop_index('idx_document_texts_full_text_search', table_name='document_texts', postgresql_using='gin')
    op.drop_index('idx_document_texts_search_ready', table_name='document_texts', postgresql_where='((text_length > 0) AND (extraction_quality IS NOT NULL))')
    op.drop_table_comment(
        'document_texts',
        existing_comment='Stores full extracted text from documents for search and chunking operations',
        schema=None
    )
    op.add_column('document_versions', sa.Column('version_metadata', sa.JSON(), nullable=True))
    op.alter_column('document_versions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('document_versions', 'version_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Numeric version identifier',
               existing_nullable=False)
    op.alter_column('document_versions', 'user_assigned_label',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Custom version label (e.g., "v2.0", "draft")',
               existing_nullable=True)
    op.alter_column('document_versions', 'is_latest_version',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment=None,
               existing_comment='Flag indicating if this is the current version',
               existing_nullable=False)
    op.drop_constraint('document_versions_storage_unique', 'document_versions', type_='unique')
    op.drop_constraint('document_versions_unique_version', 'document_versions', type_='unique')
    op.drop_index('idx_document_versions_created_at', table_name='document_versions')
    op.drop_index('idx_document_versions_document_id', table_name='document_versions')
    op.drop_index('idx_document_versions_latest', table_name='document_versions', postgresql_where='(is_latest_version = true)')
    op.drop_table_comment(
        'document_versions',
        existing_comment='Version history for documents, based on PipesHub DocumentVersion schema',
        schema=None
    )
    op.drop_column('document_versions', 'metadata')
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               comment=None,
               existing_comment='Primary UUID identifier for the document',
               existing_nullable=False)
    op.alter_column('documents', 'document_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Display name for the document (equivalent to PipesHub documentName)',
               existing_nullable=False)
    op.alter_column('documents', 'original_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Original filename as uploaded by user',
               existing_nullable=False)
    op.alter_column('documents', 'checksum',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='SHA-256 checksum for file integrity verification',
               existing_nullable=False)
    op.alter_column('documents', 'storage_provider',
               existing_type=postgresql.ENUM('local', 's3', 'azure_blob', name='storage_provider_enum'),
               server_default=None,
               comment=None,
               existing_comment='Storage backend (local/s3/azure_blob) following PipesHub multi-storage pattern',
               existing_nullable=False)
    op.alter_column('documents', 'storage_path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Full path to file in the storage system',
               existing_nullable=False)
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('pending', 'uploading', 'processing', 'completed', 'failed', name='document_status_enum'),
               server_default=None,
               comment=None,
               existing_comment='Processing status following PipesHub IndexingStatus pattern',
               existing_nullable=False)
    op.alter_column('documents', 'is_versioned_file',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'current_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'mutation_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='Flexible JSONB field for custom metadata (equivalent to PipesHub customMetadata)',
               existing_nullable=True)
    op.alter_column('documents', 'access_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='Number of times document has been accessed via GET endpoint',
               existing_nullable=False)
    op.alter_column('documents', 'last_accessed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of last document access',
               existing_nullable=True)
    op.alter_column('documents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment=None,
               existing_comment='Soft delete flag following PipesHub pattern',
               existing_nullable=False)
    op.alter_column('documents', 'is_dirty',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment=None,
               existing_comment='Flag indicating document needs re-processing (PipesHub pattern)',
               existing_nullable=False)
    op.drop_constraint('documents_storage_path_unique', 'documents', type_='unique')
    op.drop_index('idx_documents_checksum', table_name='documents')
    op.drop_index('idx_documents_created_at', table_name='documents', postgresql_where='(is_deleted = false)')
    op.drop_index('idx_documents_file_size', table_name='documents', postgresql_where='(file_size IS NOT NULL)')
    op.drop_index('idx_documents_is_dirty', table_name='documents', postgresql_where='(is_dirty = true)')
    op.drop_index('idx_documents_last_accessed', table_name='documents', postgresql_where='(last_accessed_at IS NOT NULL)')
    op.drop_index('idx_documents_last_extraction', table_name='documents', postgresql_where='(last_extraction_at IS NOT NULL)')
    op.drop_index('idx_documents_metadata', table_name='documents', postgresql_using='gin', postgresql_where='(is_deleted = false)')
    op.drop_index('idx_documents_metadata_author', table_name='documents')
    op.drop_index('idx_documents_metadata_doc_type', table_name='documents')
    op.drop_index('idx_documents_metadata_engine', table_name='documents')
    op.drop_index('idx_documents_metadata_gin', table_name='documents', postgresql_using='gin')
    op.drop_index('idx_documents_metadata_language', table_name='documents')
    op.drop_index('idx_documents_metadata_path_ops', table_name='documents', postgresql_using='gin')
    op.drop_index('idx_documents_metadata_quality_score', table_name='documents')
    op.drop_index('idx_documents_metadata_title', table_name='documents')
    op.drop_index('idx_documents_mime_extraction', table_name='documents')
    op.drop_index('idx_documents_mime_type', table_name='documents', postgresql_where='(is_deleted = false)')
    op.drop_index('idx_documents_needs_extraction', table_name='documents', postgresql_where="((metadata IS NULL) OR (metadata = '{}'::jsonb))")
    op.drop_index('idx_documents_search_composite', table_name='documents', postgresql_where="((status = ANY (ARRAY['completed'::document_status_enum, 'processing'::document_status_enum])) AND (is_deleted = false))")
    op.drop_index('idx_documents_status', table_name='documents', postgresql_where='(is_deleted = false)')
    op.drop_index('idx_documents_status_extraction', table_name='documents')
    op.drop_index('idx_documents_storage_provider', table_name='documents', postgresql_where='(is_deleted = false)')
    op.drop_index('idx_documents_tags', table_name='documents', postgresql_using='gin', postgresql_where='(is_deleted = false)')
    op.drop_index('idx_documents_updated_at', table_name='documents', postgresql_where='(is_deleted = false)')
    op.drop_table_comment(
        'documents',
        existing_comment='Main documents table storing document metadata and status, based on PipesHub MongoDB schema patterns',
        schema=None
    )
    op.alter_column('embeddings', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('embeddings', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Order of this chunk within the document',
               existing_nullable=False)
    op.alter_column('embeddings', 'chunk_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='The actual text content for this chunk',
               existing_nullable=False)
    op.alter_column('embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1024),
               comment=None,
               existing_comment='Vector embedding (1024 dimensions for BGE-M3, 1536 for OpenAI ada-002)',
               existing_nullable=True)
    op.alter_column('embeddings', 'chunk_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('embeddings', 'contains_table',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('embeddings', 'contains_list',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('embeddings', 'contains_code',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('embeddings', 'contains_equation',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('embeddings', 'contains_figure',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('embeddings', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('embeddings', 'chunk_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('embeddings', 'embedding_model',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('embeddings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when embedding was last updated',
               existing_nullable=True)
    op.drop_constraint('embeddings_unique_chunk', 'embeddings', type_='unique')
    op.drop_index('idx_embeddings_chunk_fulltext_search', table_name='embeddings', postgresql_using='gin')
    op.drop_index('idx_embeddings_chunk_index', table_name='embeddings')
    op.drop_index('idx_embeddings_chunk_metadata', table_name='embeddings', postgresql_using='gin')
    op.drop_index('idx_embeddings_chunk_type', table_name='embeddings')
    op.drop_index('idx_embeddings_citation_lookup', table_name='embeddings', postgresql_where='(page_number IS NOT NULL)')
    op.drop_index('idx_embeddings_document_id', table_name='embeddings')
    op.drop_index('idx_embeddings_page_number', table_name='embeddings', postgresql_where='(page_number IS NOT NULL)')
    op.drop_index('idx_embeddings_section', table_name='embeddings', postgresql_where='(section_heading IS NOT NULL)')
    op.drop_index('idx_embeddings_section_heading', table_name='embeddings', postgresql_where='(section_heading IS NOT NULL)')
    op.drop_index('idx_embeddings_vector', table_name='embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_table_comment(
        'embeddings',
        existing_comment='Vector embeddings for document chunks, supporting semantic search',
        schema=None
    )
    op.alter_column('processing_queue', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('processing_queue', 'priority',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('processing_queue', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('processing_queue', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('processing_queue', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('processing_queue', 'error_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('processing_queue', 'task_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('processing_queue', 'result_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('processing_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('processing_queue', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('processing_status', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('processing_status', 'stage',
               existing_type=postgresql.ENUM('upload', 'validation', 'extraction', 'chunking', 'embedding', 'indexing', 'completion', name='processing_stage_enum'),
               comment=None,
               existing_comment='Specific processing stage (upload, extraction, embedding, etc.)',
               existing_nullable=False)
    op.alter_column('processing_status', 'status',
               existing_type=postgresql.ENUM('not_started', 'in_progress', 'completed', 'failed', 'skipped', name='stage_status_enum'),
               server_default=None,
               comment=None,
               existing_comment='Status of this processing stage',
               existing_nullable=False)
    op.alter_column('processing_status', 'progress_percentage',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('processing_status', 'result_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('processing_status', 'attempt_number',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='Retry attempt number for failed stages',
               existing_nullable=False)
    op.alter_column('processing_status', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('processing_status', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_processing_status_active', table_name='processing_status', postgresql_where="(status = 'in_progress'::stage_status_enum)")
    op.drop_index('idx_processing_status_created_at', table_name='processing_status')
    op.drop_index('idx_processing_status_document_id', table_name='processing_status')
    op.drop_index('idx_processing_status_duration', table_name='processing_status', postgresql_where="((duration_ms IS NOT NULL) AND (status = 'completed'::stage_status_enum))")
    op.drop_index('idx_processing_status_failed', table_name='processing_status', postgresql_where="(status = 'failed'::stage_status_enum)")
    op.drop_index('idx_processing_status_metadata_gin', table_name='processing_status', postgresql_using='gin')
    op.drop_index('idx_processing_status_stage_status', table_name='processing_status')
    op.drop_constraint('processing_status_unique_stage', 'processing_status', type_='unique')
    op.drop_table_comment(
        'processing_status',
        existing_comment='Detailed processing stage tracking for documents',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'processing_status',
        'Detailed processing stage tracking for documents',
        existing_comment=None,
        schema=None
    )
    op.create_unique_constraint('processing_status_unique_stage', 'processing_status', ['document_id', 'stage', 'attempt_number'])
    op.create_index('idx_processing_status_stage_status', 'processing_status', ['stage', 'status'], unique=False)
    op.create_index('idx_processing_status_metadata_gin', 'processing_status', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_processing_status_failed', 'processing_status', ['document_id', 'stage', 'status', 'updated_at'], unique=False, postgresql_where="(status = 'failed'::stage_status_enum)")
    op.create_index('idx_processing_status_duration', 'processing_status', ['stage', 'duration_ms'], unique=False, postgresql_where="((duration_ms IS NOT NULL) AND (status = 'completed'::stage_status_enum))")
    op.create_index('idx_processing_status_document_id', 'processing_status', ['document_id'], unique=False)
    op.create_index('idx_processing_status_created_at', 'processing_status', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_processing_status_active', 'processing_status', ['document_id', 'stage'], unique=False, postgresql_where="(status = 'in_progress'::stage_status_enum)")
    op.alter_column('processing_status', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('processing_status', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('processing_status', 'attempt_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               comment='Retry attempt number for failed stages',
               existing_nullable=False)
    op.alter_column('processing_status', 'result_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('processing_status', 'progress_percentage',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('processing_status', 'status',
               existing_type=postgresql.ENUM('not_started', 'in_progress', 'completed', 'failed', 'skipped', name='stage_status_enum'),
               server_default=sa.text("'not_started'::stage_status_enum"),
               comment='Status of this processing stage',
               existing_nullable=False)
    op.alter_column('processing_status', 'stage',
               existing_type=postgresql.ENUM('upload', 'validation', 'extraction', 'chunking', 'embedding', 'indexing', 'completion', name='processing_stage_enum'),
               comment='Specific processing stage (upload, extraction, embedding, etc.)',
               existing_nullable=False)
    op.alter_column('processing_status', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('processing_queue', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('processing_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('processing_queue', 'result_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('processing_queue', 'task_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('processing_queue', 'error_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('processing_queue', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=True)
    op.alter_column('processing_queue', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('processing_queue', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               nullable=True)
    op.alter_column('processing_queue', 'priority',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               nullable=True)
    op.alter_column('processing_queue', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table_comment(
        'embeddings',
        'Vector embeddings for document chunks, supporting semantic search',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_embeddings_vector', 'embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_embeddings_section_heading', 'embeddings', ['section_heading'], unique=False, postgresql_where='(section_heading IS NOT NULL)')
    op.create_index('idx_embeddings_section', 'embeddings', ['section_heading'], unique=False, postgresql_where='(section_heading IS NOT NULL)')
    op.create_index('idx_embeddings_page_number', 'embeddings', ['page_number'], unique=False, postgresql_where='(page_number IS NOT NULL)')
    op.create_index('idx_embeddings_document_id', 'embeddings', ['document_id'], unique=False)
    op.create_index('idx_embeddings_citation_lookup', 'embeddings', ['document_id', 'page_number', 'section_heading'], unique=False, postgresql_where='(page_number IS NOT NULL)')
    op.create_index('idx_embeddings_chunk_type', 'embeddings', ['chunk_type'], unique=False)
    op.create_index('idx_embeddings_chunk_metadata', 'embeddings', ['chunk_metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_embeddings_chunk_index', 'embeddings', ['document_id', 'chunk_index'], unique=False)
    op.create_index('idx_embeddings_chunk_fulltext_search', 'embeddings', [sa.text("to_tsvector('english'::regconfig, chunk_text)")], unique=False, postgresql_using='gin')
    op.create_unique_constraint('embeddings_unique_chunk', 'embeddings', ['document_id', 'chunk_index'])
    op.alter_column('embeddings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when embedding was last updated',
               existing_nullable=True)
    op.alter_column('embeddings', 'embedding_model',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'text-embedding-ada-002'::character varying"),
               existing_nullable=False)
    op.alter_column('embeddings', 'chunk_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('embeddings', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'en'::character varying"),
               existing_nullable=True)
    op.alter_column('embeddings', 'contains_figure',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('embeddings', 'contains_equation',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('embeddings', 'contains_code',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('embeddings', 'contains_list',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('embeddings', 'contains_table',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('embeddings', 'chunk_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'paragraph'::character varying"),
               existing_nullable=True)
    op.alter_column('embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1024),
               comment='Vector embedding (1024 dimensions for BGE-M3, 1536 for OpenAI ada-002)',
               existing_nullable=True)
    op.alter_column('embeddings', 'chunk_text',
               existing_type=sa.TEXT(),
               comment='The actual text content for this chunk',
               existing_nullable=False)
    op.alter_column('embeddings', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment='Order of this chunk within the document',
               existing_nullable=False)
    op.alter_column('embeddings', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table_comment(
        'documents',
        'Main documents table storing document metadata and status, based on PipesHub MongoDB schema patterns',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_documents_updated_at', 'documents', [sa.text('updated_at DESC')], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index('idx_documents_tags', 'documents', ['tags'], unique=False, postgresql_using='gin', postgresql_where='(is_deleted = false)')
    op.create_index('idx_documents_storage_provider', 'documents', ['storage_provider'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index('idx_documents_status_extraction', 'documents', ['status', sa.text('last_extraction_at DESC')], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index('idx_documents_search_composite', 'documents', ['status', 'is_deleted', sa.text('last_extraction_at DESC')], unique=False, postgresql_where="((status = ANY (ARRAY['completed'::document_status_enum, 'processing'::document_status_enum])) AND (is_deleted = false))")
    op.create_index('idx_documents_needs_extraction', 'documents', ['created_at'], unique=False, postgresql_where="((metadata IS NULL) OR (metadata = '{}'::jsonb))")
    op.create_index('idx_documents_mime_type', 'documents', ['mime_type'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index('idx_documents_mime_extraction', 'documents', ['mime_type', sa.text('last_extraction_at DESC')], unique=False)
    op.create_index('idx_documents_metadata_title', 'documents', [sa.text("(metadata ->> 'title'::text)")], unique=False)
    op.create_index('idx_documents_metadata_quality_score', 'documents', [sa.text("((metadata ->> 'text_quality_score'::text)::numeric)")], unique=False)
    op.create_index('idx_documents_metadata_path_ops', 'documents', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_documents_metadata_language', 'documents', [sa.text("(metadata ->> 'language'::text)")], unique=False)
    op.create_index('idx_documents_metadata_gin', 'documents', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_documents_metadata_engine', 'documents', [sa.text("(metadata ->> 'processing_engine'::text)")], unique=False)
    op.create_index('idx_documents_metadata_doc_type', 'documents', [sa.text("(metadata ->> 'document_type'::text)")], unique=False)
    op.create_index('idx_documents_metadata_author', 'documents', [sa.text("(metadata ->> 'author'::text)")], unique=False)
    op.create_index('idx_documents_metadata', 'documents', ['metadata'], unique=False, postgresql_using='gin', postgresql_where='(is_deleted = false)')
    op.create_index('idx_documents_last_extraction', 'documents', [sa.text('last_extraction_at DESC')], unique=False, postgresql_where='(last_extraction_at IS NOT NULL)')
    op.create_index('idx_documents_last_accessed', 'documents', [sa.text('last_accessed_at DESC')], unique=False, postgresql_where='(last_accessed_at IS NOT NULL)')
    op.create_index('idx_documents_is_dirty', 'documents', ['is_dirty'], unique=False, postgresql_where='(is_dirty = true)')
    op.create_index('idx_documents_file_size', 'documents', [sa.text('file_size DESC')], unique=False, postgresql_where='(file_size IS NOT NULL)')
    op.create_index('idx_documents_created_at', 'documents', [sa.text('created_at DESC')], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index('idx_documents_checksum', 'documents', ['checksum'], unique=False)
    op.create_unique_constraint('documents_storage_path_unique', 'documents', ['storage_provider', 'storage_path'])
    op.alter_column('documents', 'is_dirty',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment='Flag indicating document needs re-processing (PipesHub pattern)',
               existing_nullable=False)
    op.alter_column('documents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment='Soft delete flag following PipesHub pattern',
               existing_nullable=False)
    op.alter_column('documents', 'last_accessed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of last document access',
               existing_nullable=True)
    op.alter_column('documents', 'access_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='Number of times document has been accessed via GET endpoint',
               existing_nullable=False)
    op.alter_column('documents', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment='Flexible JSONB field for custom metadata (equivalent to PipesHub customMetadata)',
               existing_nullable=True)
    op.alter_column('documents', 'mutation_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('documents', 'current_version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('documents', 'is_versioned_file',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('pending', 'uploading', 'processing', 'completed', 'failed', name='document_status_enum'),
               server_default=sa.text("'pending'::document_status_enum"),
               comment='Processing status following PipesHub IndexingStatus pattern',
               existing_nullable=False)
    op.alter_column('documents', 'storage_path',
               existing_type=sa.TEXT(),
               comment='Full path to file in the storage system',
               existing_nullable=False)
    op.alter_column('documents', 'storage_provider',
               existing_type=postgresql.ENUM('local', 's3', 'azure_blob', name='storage_provider_enum'),
               server_default=sa.text("'local'::storage_provider_enum"),
               comment='Storage backend (local/s3/azure_blob) following PipesHub multi-storage pattern',
               existing_nullable=False)
    op.alter_column('documents', 'checksum',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA-256 checksum for file integrity verification',
               existing_nullable=False)
    op.alter_column('documents', 'original_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Original filename as uploaded by user',
               existing_nullable=False)
    op.alter_column('documents', 'document_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Display name for the document (equivalent to PipesHub documentName)',
               existing_nullable=False)
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               comment='Primary UUID identifier for the document',
               existing_nullable=False)
    op.add_column('document_versions', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.create_table_comment(
        'document_versions',
        'Version history for documents, based on PipesHub DocumentVersion schema',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_document_versions_latest', 'document_versions', ['document_id', 'is_latest_version'], unique=False, postgresql_where='(is_latest_version = true)')
    op.create_index('idx_document_versions_document_id', 'document_versions', ['document_id'], unique=False)
    op.create_index('idx_document_versions_created_at', 'document_versions', [sa.text('created_at DESC')], unique=False)
    op.create_unique_constraint('document_versions_unique_version', 'document_versions', ['document_id', 'version_number'])
    op.create_unique_constraint('document_versions_storage_unique', 'document_versions', ['storage_provider', 'storage_path'])
    op.alter_column('document_versions', 'is_latest_version',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment='Flag indicating if this is the current version',
               existing_nullable=False)
    op.alter_column('document_versions', 'user_assigned_label',
               existing_type=sa.VARCHAR(length=100),
               comment='Custom version label (e.g., "v2.0", "draft")',
               existing_nullable=True)
    op.alter_column('document_versions', 'version_number',
               existing_type=sa.INTEGER(),
               comment='Numeric version identifier',
               existing_nullable=False)
    op.alter_column('document_versions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_column('document_versions', 'version_metadata')
    op.create_table_comment(
        'document_texts',
        'Stores full extracted text from documents for search and chunking operations',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_document_texts_search_ready', 'document_texts', ['document_id', 'extraction_quality', 'text_length'], unique=False, postgresql_where='((text_length > 0) AND (extraction_quality IS NOT NULL))')
    op.create_index('idx_document_texts_full_text_search', 'document_texts', [sa.text("to_tsvector('english'::regconfig, full_text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_document_texts_extraction_quality', 'document_texts', ['extraction_quality'], unique=False, postgresql_where='(extraction_quality IS NOT NULL)')
    op.create_index('idx_document_texts_extraction_method', 'document_texts', ['extraction_method'], unique=False)
    op.create_index('idx_document_texts_extracted_at', 'document_texts', [sa.text('extracted_at DESC')], unique=False)
    op.create_index('idx_document_texts_document_id', 'document_texts', ['document_id'], unique=False)
    op.alter_column('document_texts', 'pages_with_ocr',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='Count of pages that required OCR processing',
               existing_nullable=True)
    op.alter_column('document_texts', 'extraction_quality',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Confidence score 0.0-1.0 indicating extraction quality',
               existing_nullable=True)
    op.alter_column('document_texts', 'extraction_engine',
               existing_type=sa.VARCHAR(length=50),
               comment='Specific engine used: easyocr, tesseract, rapidocr, or native text extraction',
               existing_nullable=True)
    op.alter_column('document_texts', 'extraction_method',
               existing_type=sa.VARCHAR(length=50),
               comment='Method used for extraction: docling (native), docling_ocr (OCR applied), or fallback',
               existing_nullable=False)
    op.alter_column('document_texts', 'text_length',
               existing_type=sa.INTEGER(),
               comment='Character count of extracted text',
               existing_nullable=False)
    op.alter_column('document_texts', 'full_text',
               existing_type=sa.TEXT(),
               comment='Complete extracted text content from the document',
               existing_nullable=False)
    op.alter_column('document_texts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    # ### end Alembic commands ###
