"""initial_schema

Revision ID: 6e71b3dac76f
Revises:
Create Date: 2025-11-05 15:27:27.300944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy
import sys
import os

# Add parent directory to path to import custom types
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
from app.models import types as app_types


# revision identifiers, used by Alembic.
revision = '6e71b3dac76f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', app_types.GUID(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('alternate_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_extension', sa.String(length=10), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('storage_provider', sa.Enum('local', 's3', 'azure_blob', name='storage_provider_enum'), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('storage_bucket', sa.String(length=100), nullable=True),
    sa.Column('storage_region', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'uploading', 'processing', 'completed', 'failed', name='document_status_enum'), nullable=False),
    sa.Column('is_versioned_file', sa.Boolean(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('mutation_count', sa.Integer(), nullable=False),
    sa.Column('metadata', app_types.JSON(), nullable=True),
    sa.Column('tags', app_types.StringArray(), nullable=True),
    sa.Column('last_extraction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_embedding_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', app_types.GUID(), nullable=True),
    sa.Column('is_dirty', sa.Boolean(), nullable=False),
    sa.Column('processing_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum')
    )
    op.create_table('document_texts',
    sa.Column('id', app_types.GUID(), nullable=False),
    sa.Column('document_id', app_types.GUID(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('text_length', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('extraction_engine', sa.String(length=50), nullable=True),
    sa.Column('extraction_quality', sa.Float(), nullable=True),
    sa.Column('pages_with_ocr', sa.Integer(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('extraction_duration_ms', sa.Integer(), nullable=True),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('extraction_quality >= 0.0 AND extraction_quality <= 1.0', name='check_extraction_quality'),
    sa.CheckConstraint('text_length >= 0', name='check_text_length_positive'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('document_versions',
    sa.Column('id', app_types.GUID(), nullable=False),
    sa.Column('document_id', app_types.GUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('user_assigned_label', sa.String(length=100), nullable=True),
    sa.Column('version_note', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_extension', sa.String(length=10), nullable=False),
    sa.Column('storage_provider', sa.Enum('LOCAL', 'S3', 'AZURE_BLOB', name='storage_provider_enum'), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('storage_bucket', sa.String(length=100), nullable=True),
    sa.Column('storage_region', sa.String(length=50), nullable=True),
    sa.Column('version_metadata', app_types.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', app_types.GUID(), nullable=True),
    sa.Column('is_latest_version', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum')
    )
    op.create_table('embeddings',
    sa.Column('id', app_types.GUID(), nullable=False),
    sa.Column('document_id', app_types.GUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_tokens', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1024), nullable=True),
    sa.Column('start_position', sa.Integer(), nullable=True),
    sa.Column('end_position', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_heading', sa.String(length=500), nullable=True),
    sa.Column('subsection_heading', sa.String(length=500), nullable=True),
    sa.Column('chunk_type', sa.String(length=50), nullable=True),
    sa.Column('paragraph_index', sa.Integer(), nullable=True),
    sa.Column('semantic_density', sa.Float(), nullable=True),
    sa.Column('contains_table', sa.Boolean(), nullable=True),
    sa.Column('contains_list', sa.Boolean(), nullable=True),
    sa.Column('contains_code', sa.Boolean(), nullable=True),
    sa.Column('contains_equation', sa.Boolean(), nullable=True),
    sa.Column('contains_figure', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_queue',
    sa.Column('id', app_types.GUID(), nullable=False),
    sa.Column('document_id', app_types.GUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('processor_id', sa.String(length=255), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', app_types.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('task_params', app_types.JSON(), nullable=True),
    sa.Column('result_data', app_types.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed', 'cancelled')"),
    sa.CheckConstraint('priority >= 1 AND priority <= 10'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_status',
    sa.Column('id', app_types.GUID(), nullable=False),
    sa.Column('document_id', app_types.GUID(), nullable=False),
    sa.Column('stage', sa.Enum('upload', 'validation', 'extraction', 'chunking', 'embedding', 'indexing', 'completion', name='processing_stage_enum'), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', 'failed', 'skipped', name='stage_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('result_data', app_types.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('metadata', app_types.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(completed_at IS NULL AND duration_ms IS NULL) OR (completed_at IS NOT NULL AND duration_ms IS NOT NULL)'),
    sa.CheckConstraint('progress_percentage >= 0 AND progress_percentage <= 100'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processing_status')
    op.drop_table('processing_queue')
    op.drop_table('embeddings')
    op.drop_table('document_versions')
    op.drop_table('document_texts')
    op.drop_table('documents')
    # ### end Alembic commands ###
